"""
NSE Darvas Box Scanner - Data Downloader
=========================================
• Initial run  : Downloads full history for all NSE symbols in batches.
• Incremental  : Detects latest date per symbol and downloads only the gap.
• Rate limiting: Exponential backoff with retry queue; never skips symbols.
• Storage      : One Parquet file per symbol under data/daily/.
• Timeframes   : Weekly and monthly generated by resampling – never downloaded.
"""

from __future__ import annotations

import random
import time
from datetime import date, datetime, timedelta
from pathlib import Path
from typing import Optional

import pandas as pd
import yfinance as yf

from config import (
    BATCH_SIZE, BATCH_DELAY_SECONDS, DAILY_DIR,
    EXPONENTIAL_BASE, MAX_RETRIES, RETRY_WAIT_MINUTES,
    NIFTY50_SYMBOL, NIFTY500_SYMBOL,
)
from logger_utils import get_logger

log = get_logger("download")

# Stooq fallback suffix map
_STOOQ_SUFFIX = ".IN"   # e.g. RELIANCE.IN on stooq


# ─── Public API ───────────────────────────────────────────────────────────────

def run_download(symbols: list[str], full_refresh: bool = False) -> None:
    """
    Main entry point.  Downloads / updates Parquet files for *symbols*.
    Also downloads benchmark indices.
    """
    benchmarks = [NIFTY50_SYMBOL, NIFTY500_SYMBOL]
    all_symbols = benchmarks + symbols

    # Shuffle to break alphabetical clustering → avoids rate-limit bursts
    equity = list(symbols)
    random.shuffle(equity)
    targets = benchmarks + equity

    if full_refresh:
        log.info("FULL REFRESH requested – removing existing daily cache.")
        for sym in targets:
            p = _parquet_path(sym)
            if p.exists():
                p.unlink()

    # Split into batches
    batches = _make_batches(targets, BATCH_SIZE)
    log.info("Downloading %d symbols in %d batches (batch_size=%d)",
             len(targets), len(batches), BATCH_SIZE)

    failed: list[str] = []
    for i, batch in enumerate(batches, 1):
        log.info("Batch %d/%d – %d symbols", i, len(batches), len(batch))
        ok, bad = _download_batch(batch)
        failed.extend(bad)
        if i < len(batches):
            time.sleep(BATCH_DELAY_SECONDS)

    # Retry queue with exponential backoff
    if failed:
        _retry_failed(failed)

    log.info("Download complete.  Failed (permanent): %s", failed or "none")


def load_daily(symbol: str) -> Optional[pd.DataFrame]:
    """Load daily OHLCV DataFrame for *symbol* from Parquet cache."""
    p = _parquet_path(symbol)
    if not p.exists():
        return None
    try:
        df = pd.read_parquet(p)
        df.index = pd.to_datetime(df.index)
        df.sort_index(inplace=True)
        return df
    except Exception as e:
        log.error("Failed to load %s: %s", symbol, e)
        return None


def resample_weekly(daily: pd.DataFrame) -> pd.DataFrame:
    """Generate weekly OHLCV from daily data (week ending Sunday)."""
    return daily.resample("W-SUN", label="left", closed="left").agg(
        {"Open": "first", "High": "max", "Low": "min",
         "Close": "last", "Volume": "sum"}
    ).dropna()


def resample_monthly(daily: pd.DataFrame) -> pd.DataFrame:
    """Generate monthly OHLCV from daily data."""
    return daily.resample("MS").agg(
        {"Open": "first", "High": "max", "Low": "min",
         "Close": "last", "Volume": "sum"}
    ).dropna()


# ─── Internal helpers ─────────────────────────────────────────────────────────

def _parquet_path(symbol: str) -> Path:
    safe = symbol.replace("^", "_").replace(".", "_")
    return DAILY_DIR / f"{safe}.parquet"


def _latest_date(symbol: str) -> Optional[date]:
    df = load_daily(symbol)
    if df is None or df.empty:
        return None
    return df.index[-1].date()


def _download_batch(batch: list[str]) -> tuple[list[str], list[str]]:
    """
    Download incremental (or full) history for a batch of symbols.
    Returns (succeeded, failed).
    """
    # Determine per-symbol start dates
    start_map: dict[str, str] = {}
    for sym in batch:
        latest = _latest_date(sym)
        if latest is None:
            start_map[sym] = "2000-01-01"
        else:
            # +1 day to avoid re-downloading the last candle
            start_map[sym] = (latest + timedelta(days=1)).isoformat()

    # Group by start date to minimise API calls where possible
    # (Most incremental runs share the same start → one batch call)
    groups: dict[str, list[str]] = {}
    for sym, start in start_map.items():
        groups.setdefault(start, []).append(sym)

    succeeded, failed = [], []
    for start, syms in groups.items():
        end = (date.today() + timedelta(days=1)).isoformat()
        try:
            raw = yf.download(
                syms,
                start=start,
                end=end,
                auto_adjust=True,
                progress=False,
                threads=True,
            )
            if raw is None or raw.empty:
                log.warning("Empty data for group starting %s", start)
                failed.extend(syms)
                continue

            for sym in syms:
                df = _extract_symbol(raw, sym, len(syms))
                if df is None or df.empty:
                    log.warning("No data for %s", sym)
                    failed.append(sym)
                    continue
                _merge_and_save(sym, df)
                succeeded.append(sym)

        except Exception as exc:
            log.error("Batch download error (%s): %s", start, exc)
            failed.extend(syms)

    return succeeded, failed


def _extract_symbol(raw: pd.DataFrame, symbol: str, n_syms: int) -> Optional[pd.DataFrame]:
    """Extract single-symbol OHLCV from a multi-symbol yfinance download."""
    try:
        if n_syms == 1:
            # Single-symbol download → columns are already flat
            df = raw[["Open", "High", "Low", "Close", "Volume"]].copy()
        else:
            # Multi-symbol → MultiIndex columns
            df = raw.loc[:, (slice(None), symbol)].copy()
            df.columns = df.columns.droplevel(1)
        df = df.dropna(how="all")
        df.index = pd.to_datetime(df.index)
        return df
    except Exception as e:
        log.debug("Extraction error for %s: %s", symbol, e)
        return None


def _merge_and_save(symbol: str, new_df: pd.DataFrame) -> None:
    """Merge new data with existing Parquet and save."""
    p = _parquet_path(symbol)
    if p.exists():
        existing = pd.read_parquet(p)
        existing.index = pd.to_datetime(existing.index)
        combined = pd.concat([existing, new_df])
        combined = combined[~combined.index.duplicated(keep="last")]
        combined.sort_index(inplace=True)
    else:
        combined = new_df.sort_index()

    combined.to_parquet(p, index=True, compression="snappy")
    log.debug("Saved %s – %d rows", symbol, len(combined))


def _make_batches(items: list, size: int) -> list[list]:
    return [items[i : i + size] for i in range(0, len(items), size)]


def _retry_failed(failed: list[str]) -> None:
    """Retry failed symbols with exponential backoff."""
    remaining = list(failed)
    for attempt in range(1, MAX_RETRIES + 1):
        if not remaining:
            break
        wait = RETRY_WAIT_MINUTES * 60 * (EXPONENTIAL_BASE ** (attempt - 1))
        log.info("Retry %d/%d – waiting %.0fs for %d symbols",
                 attempt, MAX_RETRIES, wait, len(remaining))
        time.sleep(wait)

        ok, still_bad = _download_batch(remaining)
        log.info("Retry %d: %d succeeded, %d still failed", attempt, len(ok), len(still_bad))
        remaining = still_bad

    if remaining:
        log.error("Permanently failed after %d retries: %s", MAX_RETRIES, remaining[:20])
